visualfc/liteide

.gitignore, README.md, build/build_openbsd.sh, liteidex/deploy/welcome/en/install.md, liteidex/os_deploy/openbsd/liteenv/cross-arm5.env, liteidex/os_deploy/openbsd/liteenv/cross-arm6.env, liteidex/os_deploy/openbsd/liteenv/cross-darwin32.env, liteidex/os_deploy/openbsd/liteenv/cross-darwin64.env, liteidex/os_deploy/openbsd/liteenv/cross-freebsd32.env, liteidex/os_deploy/openbsd/liteenv/cross-freebsd64.env, liteidex/os_deploy/openbsd/liteenv/cross-linux32.env, liteidex/os_deploy/openbsd/liteenv/cross-linux64.env, liteidex/os_deploy/openbsd/liteenv/cross-win32.env, liteidex/os_deploy/openbsd/liteenv/cross-win64.env, liteidex/os_deploy/openbsd/liteenv/openbsd32.env, liteidex/os_deploy/openbsd/liteenv/openbsd64.env, liteidex/os_deploy/openbsd/liteenv/system.env, liteidex/src/api/liteenvapi/liteenvapi.h, liteidex/src/liteidex/goapi.go, liteidex/src/liteidex/liteapp.go, liteidex/src/plugins/litebuild/build.cpp, liteidex/src/plugins/liteenv/envmanager.cpp
I've added support for OpenBSD 5.6.  It seems to work fine on my 64-bit system except for a wierdness when running XRandR (the menus come up the height of screen #0 the first time they come up, but after that first time the menus pop up with the right height).
I haven't had a chance to try it on a 32-bit OpenBSD system yet.
=> OpenBSD 5.6

liteidex/src/plugins/liteeditor/liteeditorwidget.cpp
When drag file into the editor, then editor displays the file path, which actually the editor should open the file.
Note: I found this problem on Linux Mint cinnamon 17 and Linux Mint mate 17.
=> fixed: Drag the file into the editor, but not open file.

liteidex/liteide_de.ts, liteidex/liteide_fr.ts, liteidex/liteide_ja.ts, liteidex/liteide_ru.ts, liteidex/liteide_uk.ts, liteidex/liteide_zh.ts, liteidex/liteide_zh_TW.ts, liteidex/src/liteapp/liteappoption.ui
Fixed two misspelled English words in translations and minor grammatical error.
Specifically:
- `Enalbe` should be `Enable`
- `whell` should be `wheel`
- `it's` means "it is" and does not make sense in the context (http://www.its-not-its.info)
=> Spelling + Grammar

liteidex/deploy/welcome/en/install.md, liteidex/deploy/welcome/zh_CN/install.md
Installing Qt by downloading and compiling source code is very painful and time-consuming. On Mac OS X, we can just run `brew update && brew install qt`.
=> Updated the instruction of installing Qt on Mac OS X. Greatly reduced the installation time on Mac OS X.

liteidex/os_deploy/linux/liteenv/cross-arm5.env, liteidex/os_deploy/linux/liteenv/cross-arm6.env, liteidex/os_deploy/linux/liteenv/cross-darwin32.env, liteidex/os_deploy/linux/liteenv/cross-darwin64.env, liteidex/os_deploy/linux/liteenv/cross-freebsd32.env, liteidex/os_deploy/linux/liteenv/cross-freebsd64.env, liteidex/os_deploy/linux/liteenv/cross-win32.env, liteidex/os_deploy/linux/liteenv/cross-win64.env, liteidex/os_deploy/linux/liteenv/linux32-local.env, liteidex/os_deploy/linux/liteenv/linux32.env, liteidex/os_deploy/linux/liteenv/linux64-local.env, liteidex/os_deploy/linux/liteenv/linux64.env, liteidex/os_deploy/linux/liteenv/system.env
KDE terminal app is 'konsole', not 'kconsole'. Changing the LITEIDE_SHELL variable in the .env files opens the correct terminal.
=> Use correct terminal on KDE desktops.

liteidex/src/plugins/golangedit/golangedit.cpp
Hi there,
Using the IDE i noticed a typo in the oracle callees command.
So this fixes that. :)
=> Fix typo in oracle command call.

build/build_osx.sh, build/build_osx_clang.sh
Without this fix shell checked variable "GOPATH];" in line 50, instead of "GOPATH". And broke GOPATH logic.
=> Fix build scripts for OS X.

build/update_pkg.sh, liteidex/src/plugins/liteeditor/liteeditor.cpp
and fix
```bash
go: GOPATH entry is relative; must be absolute path: "".
```
problem  for linux users
=> disable undo,redo...options after file load up

.gitignore, liteidex/src/3rdparty/3rdparty.pro, liteidex/src/plugins/fakevimedit/fakevimedit.cpp, liteidex/src/plugins/fakevimedit/fakevimedit.h, liteidex/src/plugins/fakevimedit/fakevimedit.pro, liteidex/src/plugins/fakevimedit/fakevimedit_global.h, liteidex/src/plugins/fakevimedit/fakevimeditoption.cpp, liteidex/src/plugins/fakevimedit/fakevimeditoption.h, liteidex/src/plugins/fakevimedit/fakevimeditoption.ui, liteidex/src/plugins/fakevimedit/fakevimeditoptionfactory.cpp, liteidex/src/plugins/fakevimedit/fakevimeditoptionfactory.h, liteidex/src/plugins/fakevimedit/fakevimeditplugin.cpp, liteidex/src/plugins/fakevimedit/fakevimeditplugin.h, liteidex/src/plugins/plugins.pro
Create FakeVim plugin. This uses the fakevim from https://github.com/hluk/FakeVim to add fakevim support to liteide. So far the only option is to enable or disable fakevim.
=> Create fakevim plugin

liteidex/src/liteapp/main.cpp
This one-liner solves display problems under HiDPI display in Windows without the whole application being zoomed by the system.
=> Add HiDPI support if Qt version >= 5.6

liteidex/src/utils/processex/processex.cpp
Debugging with dlv, liteide_ctrlc_stub will be started error as liteide install dir contains white space :)
=> fix liteide_ctrlc_stub path

liteidex/src/plugins/litefind/filesearchmanager.cpp
Color for filesearchmanager highlighting has been changed from bright
yellow to light blue for easier visibility.
I believe this was a strain to the eyes before and improves visibility.
Alternatively the yellow highlighting could be kept, but the foreground text colour should be changed to black.
Before:
[![Screenshot-2019-03-25-at-11-51-54.png](https://i.postimg.cc/D0C4xpjQ/Screenshot-2019-03-25-at-11-51-54.png)](https://postimg.cc/Wqk438Pt)
After: 
[![Screenshot-2019-03-25-at-11-51-15.png](https://i.postimg.cc/7ZHQG57p/Screenshot-2019-03-25-at-11-51-15.png)](https://postimg.cc/vcKvCH0z)
=> Update filesearchmanager highlighting bg color

liteidex/deploy/welcome/en/guide.md
Use proper wording according to the Chinese version:
gocode的工作原理是从项目的依赖库.a文件中读取，所以**不能代码完成时**请更新**项目的依赖库**。
更新**依赖库**
更新当前**项目的依赖库**, ...
=> fix ambiguity in guide.md

liteidex/src/utils/fileutil/fileutil.cpp
Compile error occurred when running build_linux_qt5.sh on Linux.
`
../../../../liteidex/src/utils/fileutil/fileutil.cpp: In member function ‘bool Trash::moveToTrash(QString)’:
../../../../liteidex/src/utils/fileutil/fileutil.cpp:685:24: error: incomplete type ‘QDateTime’ used in nested name specifier
info += QDateTime::currentDateTime().toString("yyyy-MM-ddThh:mm:ss");
^~~~~~~~~~~~~~~
Makefile:386: recipe for target '.obj/release-shared/fileutil.o' failed
`
I added a header file to solve this problem.
=> Fix fileutil.cpp builld error on Linux

liteidex/src/plugins/golangplay/goplaybrowser.cpp
When the autocomplete added new imports, it was added in a new block.
I was thinking about adding a format button, but it was so hard to understand it.
=> Made Go playground default content to fmt compatible.

liteidex/src/plugins/golangedit/golangedit.cpp, liteidex/src/plugins/golangedit/golangedit.h, liteidex/src/plugins/golangedit/golangfilesearch.cpp, liteidex/src/plugins/golangedit/golangfilesearch.h
This PR adds a `Find usages (Module/GOPATH) skip tests` command.
This can be useful is you want to find out how a function call is used or a variable is initialised and want to spend time filtering out test files.
Current PR needs [this](https://github.com/visualfc/gotools/pull/13) to be merged.
=> liteidex/src/plugins/golangedit: add Find Usages and skip tests command.

liteidex/liteide_tr.ts
Corrected Turkish Language Translation.
Now it is compatible with new version of LiteIDE.
=> Corrected Turkish Language Translation

liteidex/src/plugins/golangplay/goplaybrowser.cpp, liteidex/src/plugins/golangplay/goplaybrowser.h
Running go playground with a keyboard shortcut, Ctrl+Alt+R as a default
=> Running go playground with a keyboard shortcut

liteidex/src/plugins/terminal/terminal.cpp, liteidex/src/utils/vterm/vtermwidget.cpp, liteidex/src/utils/vterm/vtermwidget.h, liteidex/src/utils/vterm/vtermwidgetbase.cpp, liteidex/src/utils/vterm/vtermwidgetbase.h
Hello visualfc,
i wrote a little patch to fix a problem with the terminal plugin font on freebsd (all versions). Without this, the selected font renders unusable on my system. I successfully tested it on freebsd 13.0 and 13.1. Maybe you find it useful. I removed  a few ifdefs there, although i couldn´t check the other platforms. But I think the code should work everywhere. 
best regards
=> inherit font setting for terminal

liteidex/src/liteapp/editormanager.cpp, liteidex/src/liteapp/editormanager.h
Next and previous tab can be configured with keyboard shortcuts, default are the same as before:
Alt+(Shift+)Tab for Mac
Ctrl+(Shift+)Tab for others
=> Next and previous tab can be configured with keyboard shortcuts

build/build_netbsd.sh
Meanwhile, the build script included in this commit is sufficient to successfully build LiteIDE on NetBSD. It would be very nice if it could be included in the official branch so that interested parties on NetBSD have faster access to it. Basically the script is based on the variant of OpenBSD, with a small addition or changes.
=> Support building on NetBSD (tested on NetBSD/amd 10.0_BETA)

liteidex/src/plugins/litefind/filesearch.cpp
So the user can still edit directory if (s)he wants to, also search by enter when https://github.com/visualfc/liteide/pull/1279 is merged too.
=> Search file's current folder button focuses directory combo
