visualfc/liteide

- liteidex/deploy/liteapp/kms/default.kms
-Windows 7 64bits-
Added:
Paste="Shift+Insert; Ctrl+V"
> Shift-Insert (Paste) not working on X27.1

- liteidex/deploy/liteeditor/color/clearday.xml
> Add new clear color scheme (clearday)

- liteidex/deploy/liteeditor/kate/yaml.xml
I've added .yaml file support, which enables syntax highlighting and proper indentation with spaces.
> added kate yaml syntax file

- liteidex/deploy/welcome/zh_CN/install.md
update the URL of the binary download
> update the URL of the binary download

- liteidex/src/plugins/golangfmt/golangfmt.cpp
This should fix https://github.com/visualfc/liteide/issues/439 - gofmt on save is broken
Also add more clear logging for easy debug this problem in future.
> Fix gofmt on save.

- liteidex/liteide_tr.ts
Hello, thanks for your effort to build this good, promising and open source golang IDE.
I just created the `liteide_tr.ts` translation file and translated all of its contents to `Turkish (tr_TR)`
> Added Turkish translations

- liteidex/liteide_tr.ts
> Escape all turkish characters to corresponding XML entities #545

- liteidex/src/liteapp/optionswidget.ui
> better syntax

- liteidex/liteide_ru.ts
two typos in Russian translation
> Fix Russian translation typo

- liteidex/deploy/liteeditor/kate/less.xml
This LESS syntax highlighting file covers:
* single line comment
* nested rule sets support
* immediate rule inside @media directive
* @media directive improvements
* tweaks in &lt;itemDatas&gt;
> Add LESS syntax highlighting file

- liteidex/liteide_fr.ts
not the most useful pull request you've seen..
> corrected a little mistake in french

- liteidex/liteide_uk.ts
Mostly style and typo corrections. Still incomplete and requires proofreading, don't have enough time to complete it, though.
> Minor update to Ukrainian translation

- liteidex/deploy/welcome/en/install.md
Tested on Ubuntu Mate 16.04 on Odroid-U3 armhf, works OK.
> Add: Ubuntu 16.04, changed packages libqtcore4 and libqtgui4.

- liteidex/deploy/liteapp/qss/default.qss
Fixing #754  so that it is visually more intuitive
> Changing the style for tab bar selection

- liteidex/deploy/liteapp/qss/black.qss
- liteidex/deploy/liteapp/qss/evilworks.qss
> Enhancing themes so that active tab is more intuitive

- liteidex/deploy/welcome/en/install.md
Fix #777 with successful build on Qt 5.5
> Update Mac OS build instructions

- liteidex/deploy/liteapp/qss/vs-dark-hdpi.qss
- liteidex/deploy/liteapp/qss/vs-dark.qss
Fixing vs-dark.qss in H-DPI scaling causes deformation problems and improves some Widget themes
> Fixing vs-dark.qss H-DPI scaling causes deformation problems

- liteidex/src/api/liteeditorapi/liteeditorapi.h
- liteidex/src/plugins/liteeditor/liteeditorwidgetbase.cpp
- liteidex/src/plugins/liteeditor/liteeditorwidgetbase.h
Like [Eclipse Mark Occurrences](http://www.eclipse.org/pdt/help/html/mark_occurrences.htm).
> Add "Mark Occurrences" function that marks selections and findings.

- liteidex/deploy/liteapp/qss/sublime.qss
Scroll bars were all bright but the sublime-theme is dark, so I added a dark style for scroll bars.
> Added style for scroll bars in sublime.qss

- liteidex/src/plugins/golangedit/golanghighlighter.cpp
1. Use state matchine to catch fucntion declarations, so we are able to distinguish the function calls and function declarations. 
2. Catch the the function call formats and hightlight them.
> Highlight function call. 

- build/build_linux_fedora27_x64.sh
- liteidex/deploy/welcome/en/install.md
Added the steps I took to get liteide working on Fedora 27.
> Fedora 27 build

- liteidex/liteide_ru.ts
Hello.
update translation in liteide_ru.ts
Best Regards, Ilya Pavlov
> update string in liteide_ru.ts

- liteidex/liteide_fr.ts
- liteidex/src/plugins/golangedit/golangedit.cpp
With also 2 string translations added in src/plugins/golangedit/golangedit.cpp.
> French translation fully defined

- liteidex/deploy/litebuild/gosrc.xml
I'm using this on personal and job projects. Hope it helps someone else with complex builds not covered by the go toolchain.
Cheers,
Diego
> Added support to build projects using make and customizable makefile

- liteidex/deploy/liteapp/qss/detroit-future.qss
- liteidex/deploy/liteeditor/color/detroit-future.xml
> Adding 'Detroit Future' theme to App, Editor

- liteidex/deploy/liteapp/qss/one-dark.qss
- liteidex/deploy/liteeditor/color/one-dark.xml
> feat(theme): add one-dark color theme

- liteidex/deploy/liteeditor/kate/makefile.xml
add syntax highlight for makefile, 
from kate repo: https://invent.kde.org/frameworks/syntax-highlighting/-/blob/master/data/syntax/makefile.xml
> A kate/makefile.xml: add syntax for makefile

- build/build_freebsd.sh
- build/build_freebsd_g++.sh
- build/build_linux.sh
- build/build_linux_debian72_x64.sh
- build/build_linux_fedora27_x64.sh
- build/build_linux_qt4.sh
- build/build_linux_qt4_webkit.sh
- build/build_linux_qt5.sh
- build/build_linux_webkit.sh
- build/build_openbsd.sh
- build/build_openbsd_g++.sh
- liteidex/deploy/welcome/en/changes.md
- liteidex/deploy/welcome/zh_CN/changes.md
- liteidex/src/3rdparty/ptyqt/core/conptyprocess.cpp
- liteidex/src/3rdparty/ptyqt/core/conptyprocess.h
- liteidex/src/3rdparty/ptyqt/core/iptyprocess.h
- liteidex/src/3rdparty/ptyqt/core/unixptyprocess.cpp
- liteidex/src/3rdparty/ptyqt/core/unixptyprocess.h
- liteidex/src/3rdparty/ptyqt/core/winptyprocess.cpp
- liteidex/src/3rdparty/ptyqt/core/winptyprocess.h
- liteidex/src/liteapp/liteapp.pro
- liteidex/src/liteide/liteide.pro
- liteidex/src/plugins/terminal/terminal.cpp
- build for freebsd/openbsd 
- liteapp library use IDE_LIBRARY_PATH for bsd
- update build_xxx.sh 
- ptyqt processList  ( 0 - not supoort, 1 - this, 2 has run process list)
> support freebsd/openbsd

- liteidex/src/3rdparty/ptyqt/core/unixptyprocess.cpp
fix https://github.com/visualfc/liteide/issues/1123
> ptyqt: support alpine linux
